server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image_sharing_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
