server:
  port: 9999
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC
      username: root
      password: 111111
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#相当于mybatis-config.xml
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
#  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.enjoy.entity